### PR TITLE
New component: Postcal code validator

### PR DESCRIPTION
**Pull request by MichaelT372**
Conditionally validates the postcode field for a US format zip code if US is selected as the country, a country has not been selected yet or if there is no country field.

Allows blank zip code if zip code is not required.

Feature flagged behind option PostalCodeValidator (default false).

Test url: https://protect.worldwildlife.org/page/53064/donate/1?assets=postal-code-validator&debug=log

I've set up the feature flag to be true on this page via a code block.

### CODE REVIEW

**Comment by MichaelT372** [comment]
This has been updated with Bryan's requested changes.

Now it does live formatting of the postcode value to cover these scenarios:

######### > #####-####
#####+#### > #####-####
##### #### > #####-####

On blur, it will show the error message if the postcode doesn't match a valid 5 or 9 digit value.

On form validate, it will also check the field value and if invalid, prevent form submission and scroll to the field.

Test url: https://protect.worldwildlife.org/page/53064/donate/1?assets=postal-code-validator&debug=log

**Comment by MichaelT372** [comment]
There are still some questions regarding the TidyContact integration, let's hold off on merging this until those are answered.

**Comment by MichaelT372** [comment]
@fernanDOTdo this is now ready to be reviewed and merged. 

The component supporters 3 dividers (+ - and space) and they are configured via the tidycontact setting us_zip_divider. It should play nice with TidyContact.

**Comment by MichaelT372** [comment]
For testing with tidy contact and customisable divider, I've set this up on RAN here https://act.ran.org/page/60781/donate/1?assets=postcode-validator

**Review by fernanDOTdo — APPROVED** [review]

**Pull request merged**
